name: light_chat_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.0
  uuid: ^2.0.1
  version: ^1.0.0
  basic_utils: ^2.4.3
  lombok: ^0.0.5
  encrypt: ^4.0.0
  pointycastle: ^1.0.2
  json_annotation: ^3.0.0
  pedantic: ^1.8.0
  crypto: ^2.1.3

dev_dependencies:
  # pedantic: ^1.8.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  test: ^1.6.0
