name: light_chat_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  path: ^1.6.0
  uuid: ^3.0.0
  version: ^2.0.0
  basic_utils: ^3.0.0
  encrypt: ^5.0.0
  pointycastle: ^3.0.0
  json_annotation: ^4.0.0
  pedantic: ^1.8.0
  crypto: ^3.0.0
  light_chat_core:
    path: ../core/

dev_dependencies:
  # pedantic: ^1.8.0
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
  test: ^1.6.0
