name: light_chat_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.1 <3.0.0"

publish_to: none

dependencies:
  light_chat_core:
    path: ../core/

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
  lints: ^1.0.1
  test: ^1.6.0
