name: Dart Client CI (Windows)

on: [push]

jobs:
  build:

    runs-on: windows-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: cd dart/client && pub get
    - name: Compile to native
      run: cd dart/client && bash ./build.bat
#     - name: Run tests
#       run: pub run test
