name: Dart Client

on:
  push:
    paths:
      - "dart/**"
      - "dart/*"
      - "dart/"
  release:
    types: # This configuration does not affect the page_build event above
      - created

# jobs:
#   build:

#     runs-on: ubuntu-latest

# container:
#       image:  google/dart:latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: Install dependencies
#       run: cd dart/client && pub get
#     - name: Script permission
#       run: cd dart/client && chmod +x ./build.sh
#     - name: Compile to native
#       run: cd dart/client && bash ./build.sh
#     - name: Run tests
#       run: pub run test
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: client-linux
            and: "&&"
          - os: macOS-latest
            output-name: client-mac
            and: "&&"
          - os: windows-latest
            output-name: client-windows.exe
            and: ";"
    # container:
    #   image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master
      - name: Cache Dart packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dart-
      - name: Install dependencies
        run: cd dart/core ${{ matrix.and }} pub get
      - run: cd dart/client ${{ matrix.and }} pub get
      - run: cd dart/client ${{ matrix.and }} mkdir build
      - name: Compile to native
        run: cd dart/client ${{ matrix.and }} dart2native bin/main.dart -v -o build/${{ matrix.output-name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: Compiled Native Artifacts
          # Directory containing files to upload
          path: dart/client/build/
#     - name: Run tests
#       run: pub run test
