name: Dart Client

on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

    # container:
#       image:  google/dart:latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: Install dependencies
#       run: cd dart/client && pub get
#     - name: Script permission
#       run: cd dart/client && chmod +x ./build.sh
#     - name: Compile to native
#       run: cd dart/client && bash ./build.sh
#     - name: Run tests
#       run: pub run test
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: client-linux
            shell: bash
          - os: macOS-latest
            output-name: client-mac
            shell: bash
          - os: windows-latest
            output-name: client-windows.exe
            shell: cmd
    # container:
    #   image:  google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - uses: DanTup/gh-actions/setup-dart@master
    - name: Install dependencies
      run: ${{ matrix.shell }} cd dart/client && pub get
    - run: ${{ matrix.shell }} cd dart/client && mkdir build
    - name: Compile to native
      run: ${{ matrix.shell }} cd dart/client && dart2native bin/main.dart -v -o build/client-${{ matrix.output-name }}
#     - name: Run tests
#       run: pub run test
